name: Crear rama desde main 

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Nombre de la nueva rama'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio manualmente con autenticación
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "murillowilmar1"
          git config --global user.email "murillowilmar1@gmail.com"

          # Clonar con autenticación explícita
          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} repo
          cd repo

          # Crear nueva rama desde main
          git checkout -b ${{ github.event.inputs.branch_name }} origin/main

          # Subir la nueva rama
          git push origin ${{ github.event.inputs.branch_name }}